# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDebugger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestDebugger
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

  target 'TestDebuggerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestDebugger-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestDebugger-tvOS

  target 'TestDebugger-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
